ExcelToSqlite/Models/Home.cs
using System.Collections.Generic;
using ExcelToSqlite.Sources;
using System.Linq;
using System.Data;
using System;
using ExcelToSqlite.Exports.Sqlite;
using System.Web.Mvc;

namespace ExcelToSqlite.Models
{
    public class HomeIndex
    {
        public DataSetProviderOptions FileOptions { get; set; }
    }

    public class ExportOptions
    {
        public string ExportFileName { get; set; }
        public IList<ExportOptionsTable> Tables { get; set; }
        public IEnumerable<SelectListItem> ColumnTypes { get; set; }

        public void Populate()
        {
            var ColTypes = new List<SelectListItem>();
            foreach (var EValue in Enum.GetValues(typeof(SQLiteColumnType)))
            {
                ColTypes.Add(new SelectListItem() { Text = EValue.ToString(), Value = ((int)EValue).ToString() });
            }
            ColumnTypes = ColTypes;

            var SourceFileName = System.IO.Path.GetFileNameWithoutExtension(SessionSource.SourceFileOriginalName);
            ExportFileName = SourceFileName + ".sqlite";
        }

        public void PopulateFrom(DataSet DS)
        {
            Populate();

            Tables = new List<ExportOptionsTable>();

            foreach (DataTable Table in DS.Tables)
            {
                var OptionsTable = new ExportOptionsTable();

                OptionsTable.Name = Table.TableName;
                OptionsTable.NewName = OptionsTable.Name;

                OptionsTable.Columns = new List<ExportOptionsTableColumn>();
                var ColumnsNames = (from DataColumn C in Table.Columns select C.ColumnName).ToList();
                foreach (var ColName in ColumnsNames)
                {
                    var Col = new ExportOptionsTableColumn();
                    Col.Name = ColName;
                    Col.NewName = Col.Name.Replace(" ", "_");
                    OptionsTable.Columns.Add(Col);
                }

                OptionsTable.ShouldIncludeInExport = true;

                Tables.Add(OptionsTable);
            }
        }
    }

    public class ExportOptionsTable
    {
        public string Name { get; set; }
        public string NewName { get; set; }
        public bool ShouldIncludeInExport {get; set;}

        public IList<ExportOptionsTableColumn> Columns { get; set; }
    }

    public class ExportOptionsTableColumn
    {
        public string Name { get; set; }
        public string NewName { get; set; }
        public SQLiteColumnType ColumnType { get; set; }
    }
}

ExcelToSqlite/Controllers/ErrorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ExcelToSqlite.Controllers
{
    public class ErrorsController : Controller
    {
        // GET: Errors
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult NotFound()
        {
            return View();
        }
    }
}

ExcelToSqlite/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ExcelToSqlite.Exports.Sqlite;
using ExcelToSqlite.Models;
using ExcelToSqlite.Sources;

namespace ExcelToSqlite.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Options()
        {
            if (SessionSource.DataSource == null)
            {
                return RedirectToAction("Index");
            }

            var Data = new ExportOptions();
            Data.PopulateFrom(SessionSource.ParseDataSet());
            
            return View(Data);
        }

        [HttpPost]
        public ActionResult Export(ExportOptions Data)
        {            
            var SqlFile = new SQLiteFile(Guid.NewGuid().ToString() + ".sqlite");
            SqlFile.InsertData(SessionSource.ParseDataSet(), Data);

            if (String.IsNullOrWhiteSpace(Data.ExportFileName)) {
                Data.ExportFileName = Guid.NewGuid().ToString() + ".sqlite";
            }

            return File(SqlFile.GetFileStream(), "application/octet-stream", Data.ExportFileName);
        }
    }
}

ExcelToSqlite/Controllers/PagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ExcelToSqlite.Controllers
{
    public class PagesController : Controller
    {
        // GET: Pages
        public ActionResult Resources()
        {
            return View();
        }
    }
}

ExcelToSqlite/Controllers/UploadController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Excel;
using ExcelToSqlite.Sources;
using ExcelToSqlite.Sources.Data_Providers;
using ExcelToSqlite.Sources.Excel;


namespace ExcelToSqlite.Controllers
{
    public class UploadController : Controller
    {
        [HttpPost()]
        public ActionResult Excel(HttpPostedFileBase File,  DataSetProviderOptions FileOptions)
        {
            var FileName = SaveFile(File);
            SessionSource.SourceFileOriginalName = File.FileName;

            if (Path.GetExtension(File.FileName) == ".xls" || Path.GetExtension(File.FileName) == ".xlsx")
            {
                SessionSource.SourceFileType = Sources.SourceType.Excel;
                SessionSource.DataSource = new ExcelDataProvider(FileOptions, FileName);
            }
            else 
            {
                SessionSource.SourceFileType = Sources.SourceType.CSV;
                SessionSource.DataSource = new CSVDataProvider(FileOptions, FileName);
            }

                       
            return RedirectToAction("Options", "Home");
        }

        private string SaveFile(HttpPostedFileBase File)
        {
            var BasePath = Server.MapPath("~/temp/files/");
            var FileName = String.Format("{0:}_{1}", Guid.NewGuid().ToString(), File.FileName);
            File.SaveAs(BasePath + FileName);
            return BasePath + FileName;
        }
    }
}

ExcelToSqlite/Views/Home/Index.cshtml
@model ExcelToSqlite.Models.HomeIndex

@{
    ViewBag.Title = "Convert Files To SQLite Online";
}


    <h3>Convert CSV or Excel File To SQLite</h3>
    <p>
        This tool will convert a CSV or Excel xls/xlsx file to a SQLite database file. Upload your file below to begin.
    </p>

    @using (Html.BeginForm("Excel", "Upload", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <div class="panel panel-default">
            <div class="panel-heading">Upload CSV or Excel File</div>
            <div class="panel-body">
                <div class="form-group">
                    <label>File To Convert</label>
                    <input type="file" name="File" />
                </div>
                <div class="form-group">
                    <div class="checkbox">
                        <label>
                            @Html.CheckBoxFor(x => x.FileOptions.IsFirstRowAsColumnNames)
                            First Row Contains Column Names
                        </label>
                    </div>
                </div>

                <input type="submit" value="Upload" class="btn btn-primary btn-lg btn-block" />
            </div>
        </div>
    }

    <p>
        <h3>What Is SQLite?</h3>
        <p>
            <a href="http://sqlite.org" target="_blank">SQLite</a> is a popular serverless SQL database, 
            used to embed data locally in an application. SQLite is commonly used in mobile apps/games,
            as well as other settings where a local database can come in handy.
        </p>

        <p>
            There are many SQLite libraries available in various programming languages - such as C/C++, .NET, Objective-C and Java.
            For more information, see our <a href="@Url.Action("Resources", "Pages")">resources</a> page.
        </p>
    </p>

ExcelToSqlite/Views/Home/Options.cshtml
@model ExcelToSqlite.Models.ExportOptions
@{
    ViewBag.Title = "Conversion Options";
}

    <h3>@ViewBag.Title</h3>
    @using (Html.BeginForm("Export", "Home"))
    {

        <div class="panel panel-primary">
            <div class="panel-heading">Table Options</div>
            <div class="panel-body">

                @for (int i = 0; i < Model.Tables.Count; i++)
                {
                    <div class="panel panel-info">
                        <div class="panel-heading">@Model.Tables[i].Name</div>
                        <div class="panel-body">

                            <div class="form-group">
                                <div class="checkbox">
                                    <label>
                                        @Html.CheckBoxFor(x => x.Tables[i].ShouldIncludeInExport)
                                        Include In Export
                                    </label>
                                </div>
                            </div>
                            <div class="form-group">
                                <label>Table Name</label>
                                @Html.HiddenFor(x => x.Tables[i].Name)
                                @Html.TextBoxFor(x => x.Tables[i].NewName, new { @class = "form-control" })
                            </div>

                            <h5>Columns</h5>

                            <div class="table-responsive table-bordered">
                                <table class="table">
                                    <thead>
                                        <tr>
                                            <th>Column Name</th>
                                            <th>New Column Name</th>
                                            <th>Column Type</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @for (int col = 0; col < Model.Tables[i].Columns.Count(); col++)
                                        {
                                            <tr>
                                                @{
                                            var Column = Model.Tables[i].Columns[col];
                                                }
                                                @Html.HiddenFor(x => x.Tables[i].Columns[col].Name)
                                                <td>@Column.Name</td>
                                                <td>
                                                    @Html.TextBoxFor(x => x.Tables[i].Columns[col].NewName, new { @class = "form-control" })
                                                </td>
                                                <td>
                                                    @Html.DropDownListFor(x => x.Tables[i].Columns[col].ColumnType, Model.ColumnTypes, new { @class = "form-control" })
                                                </td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    
                    if (Model.Tables.Count >= 3 && i == 1)
                    {
                        <div class="panel panel-info">
                            <div class="panel-heading">From Our Sponsors</div>
                            <div class="panel-body">
                                <div class="col-lg-6">
                                    <!-- Mid Ad 1 -->
                                    <ins class="adsbygoogle"
                                         style="display:inline-block;width:336px;height:280px"
                                         data-ad-client="ca-pub-1457687322736119"
                                         data-ad-slot="3895022381"></ins>
                                    <script>
                                        (adsbygoogle = window.adsbygoogle || []).push({});
                                    </script>
                                </div>
                                <div class="col-lg-6">
                                    <!-- Mid Ad 2 -->
                                    <ins class="adsbygoogle"
                                         style="display:inline-block;width:336px;height:280px"
                                         data-ad-client="ca-pub-1457687322736119"
                                         data-ad-slot="5371755587"></ins>
                                    <script>
                                        (adsbygoogle = window.adsbygoogle || []).push({});
                                    </script>
                                </div>
                            </div>
                        </div>
                    }
                }

            </div>
        </div>

        <div class="panel panel-primary">
            <div class="panel-heading">File Options</div>
            <div class="panel-body">
                <div class="form-group">
                    <label>Final File Name</label>
                    @Html.TextBoxFor(x => x.ExportFileName, new { @class = "form-control" })
                </div>
            </div>
        </div>

        <div class="panel panel-info">
            <div class="panel-heading">From Our Sponsors</div>
            <div class="panel-body">
                <div class="col-lg-6">
                    <!-- Convert Ad 1 -->
                    <ins class="adsbygoogle"
                         style="display:inline-block;width:336px;height:280px"
                         data-ad-client="ca-pub-1457687322736119"
                         data-ad-slot="3895022381"></ins>
                    <script>
                        (adsbygoogle = window.adsbygoogle || []).push({});
                    </script>
                </div>
                <div class="col-lg-6">
                    <!-- Convert Ad 2 -->
                    <ins class="adsbygoogle"
                         style="display:inline-block;width:336px;height:280px"
                         data-ad-client="ca-pub-1457687322736119"
                         data-ad-slot="5371755587"></ins>
                    <script>
                        (adsbygoogle = window.adsbygoogle || []).push({});
                    </script>
                </div>
            </div>
        </div>

        <div class="form-group">
            <input type="submit" value="Convert!" class="btn btn-success btn-lg btn-block" />
        </div>

    <div>
        <h3>Like this tool? Spread the word!</h3>
        
        <div>
            <div class="addthis_sharing_toolbox"></div>
        </div>
    </div>
    }

ExcelToSqlite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="A tool to convert an Excel or CSV file to a SQLite file">
    <meta name="author" content="">

    <meta name="msvalidate.01" content="7B39446531F7B4D656485D21BFB20BBB" />

    <title>@ViewBag.Title - Convert To SQLite</title>

    <!-- Bootstrap Core CSS -->
    <link href="~/css/bootstrap.min.css" rel="stylesheet">

    <!-- MetisMenu CSS -->
    <link href="~/css/plugins/metisMenu/metisMenu.min.css" rel="stylesheet">

    <!-- Timeline CSS -->
    <link href="~/css/plugins/timeline.css" rel="stylesheet">

    <!-- Custom Theme CSS -->
    <link href="~/css/sb-admin-2.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="~/css/style.css" rel="stylesheet">

    <!-- Morris Charts CSS -->
    <link href="~/css/plugins/morris.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="~/font-awesome-4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    <script>
    (function (i, s, o, g, r, a, m) {
        i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
            (i[r].q = i[r].q || []).push(arguments)
        }, i[r].l = 1 * new Date(); a = s.createElement(o),
        m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
    })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

    ga('create', 'UA-55011492-1', 'auto');
    ga('send', 'pageview');

    </script>

    <!-- addthis-->
    <script async type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-5729808c75d6511a"></script>
</head>
<body>
    <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="col-md-6 col-md-push-3">
                <div class="navbar-header">
                    <a class="navbar-brand" href="~/"><h1>Convert To SQLite Online</h1></a>
                </div>
                <!-- /.navbar-header -->
            </div>

            <ul class="nav navbar-top-links navbar-right">
                <li>
                    <a href="~/">Home</a>
                </li>
                <li>
                    <a href="@Url.Action("Resources", "Pages")">Resources</a>
                </li>
            </ul>
        </nav>

        <div id="page-wrapper" class="clearfix">
            <div class="col-md-8 col-md-push-2 ad-wrapper">
                <aside>From our sponsors:</aside>

                <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
                <!-- Header Responsive 1 -->
                <ins class="adsbygoogle"
                     style="display:block"
                     data-ad-client="ca-pub-1457687322736119"
                     data-ad-slot="5664255584"
                     data-ad-format="auto"></ins>
                <script>
                    (adsbygoogle = window.adsbygoogle || []).push({});
                </script>
            </div>

            <div class="col-md-8 col-md-push-3">
                <div class="col-md-10">
                    @RenderBody()
                </div>
            </div>
            
            <div class="col-md-8 col-md-push-2  ad-wrapper">
                <aside>From our sponsors:</aside>

                <!-- Header Responsive 2 -->
                <ins class="adsbygoogle"
                     style="display:block"
                     data-ad-client="ca-pub-1457687322736119"
                     data-ad-slot="9643469989"
                     data-ad-format="auto"></ins>
                <script>
                    (adsbygoogle = window.adsbygoogle || []).push({});
                </script>
            </div>

        </div>
            <!-- /#page-wrapper -->

        </div>
        <!-- /#wrapper -->

    <!-- jQuery Version 1.11.0 -->
    <script src="~/js/jquery-1.11.0.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="~/js/bootstrap.min.js"></script>

    <!-- Metis Menu Plugin JavaScript -->
    <script src="~/js/plugins/metisMenu/metisMenu.min.js"></script>
    
   <!-- Custom Theme JavaScript -->
   <script src="~/js/sb-admin-2.js"></script>

</body>

</html>